### ISSUE TITLE
Cannot publish view, throws error (acorn v4?)

### ISSUE THREAD

**Issue by fgd007** [supermundano/sage-the-events-calendar#8]
In the last publication step I get this error:

In TheEventsCalendarServiceProvider.php line 7:
                                                                                                                                    
`Class Supermundano\Sage\TheEventsCalendar\TheEventsCalendarServiceProvider cannot extend final class Roots\Acorn\ServiceProvider`

Could this have something to do with using the latest version of Acorn (version 4.2.2)?

**Comment by cfaria** [comment]
Hi @fgd007, thanks for your heads up!

Can you try with dev-main? If you confirm this last commit fixes the issue I'd tag a new version.

Thank you!

**Comment by fgd007** [comment]
@cfaria thanks, works! I was about to submit a PR with the same solution, as described here https://roots.io/acorn/docs/upgrading-acorn/

**Comment by cfaria** [comment]
Cool!

Tagged 1.0.6 ;)
